# Generated by Django 3.2.6 on 2022-03-15 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_alter_walletprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletprofile',
            name='wallet_address',
            field=models.CharField(default=122, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='walletprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
