# Generated by Django 3.2.6 on 2022-03-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_walletprofile_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletprofile',
            name='wallet_address',
            field=models.CharField(default=111, max_length=15),
            preserve_default=False,
        ),
    ]
