# Generated by Django 3.2.6 on 2022-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_walletprofile_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletprofile',
            name='wallet_address',
            field=models.CharField(max_length=47),
        ),
    ]
