# Generated by Django 3.2.6 on 2022-03-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0002_auto_20220315_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='user',
        ),
    ]
