# Generated by Django 3.2.6 on 2022-03-16 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0006_accountactivation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountactivation',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='refer.profile'),
            preserve_default=False,
        ),
    ]
