# Generated by Django 3.2.6 on 2022-03-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0007_accountactivation_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountactivation',
            name='profile',
        ),
    ]
