# Generated by Django 3.2.6 on 2022-03-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0008_remove_accountactivation_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Confirmed'), (1, 'Confirmed')], default=0),
        ),
    ]
