# Generated by Django 3.2.6 on 2022-03-17 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0009_withdrawalrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='USDT_Amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(20, 'Minimum_Withdrawal $20'), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
