# Generated by Django 3.2.6 on 2022-03-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0011_alter_withdrawalrequest_usdt_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='total_earning',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
