# Generated by Django 3.2.6 on 2022-03-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0012_withdrawalrequest_total_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='total_earning',
            field=models.IntegerField(),
        ),
    ]
