# Generated by Django 3.2.6 on 2022-03-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0014_alter_withdrawalrequest_usdt_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='total_earning',
        ),
        migrations.AddField(
            model_name='profile',
            name='total_earning',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
