# Generated by Django 3.2.6 on 2022-03-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0015_auto_20220317_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
