# Generated by Django 3.2.6 on 2022-03-17 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0016_profile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='USDT_Amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Minimum_Withdrawal $20')]),
        ),
    ]
