# Generated by Django 3.2.6 on 2022-03-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0018_remove_profile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_earning',
            field=models.PositiveIntegerField(),
        ),
    ]
