# Generated by Django 3.2.6 on 2022-03-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0023_alter_withdrawalrequest_usdt_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_earning',
        ),
        migrations.AddField(
            model_name='profile',
            name='expenses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accountactivation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disapprove'), (1, 'Approve'), (2, 'Deny')], default=0),
        ),
    ]
