# Generated by Django 3.2.6 on 2022-03-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0025_profile_total_earn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_earn',
        ),
    ]
