# Generated by Django 3.2.6 on 2022-03-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0026_remove_profile_total_earn'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_earn',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
