# Generated by Django 3.2.6 on 2022-03-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0027_profile_total_earn'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
