# Generated by Django 3.2.6 on 2022-03-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0028_profile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_earn',
        ),
        migrations.AddField(
            model_name='profile',
            name='total_earnings',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
