# Generated by Django 3.2.6 on 2022-03-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0030_remove_profile_total_earnings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='balance',
            new_name='pre_earn',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expenses',
        ),
        migrations.AddField(
            model_name='profile',
            name='earn',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
