# Generated by Django 3.2.6 on 2022-03-19 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0031_auto_20220318_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pre_earn',
        ),
    ]
