# Generated by Django 3.2.6 on 2022-03-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0032_remove_profile_pre_earn'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='balance',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='wallet_address',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
