# Generated by Django 3.2.6 on 2022-03-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0036_accountactivation_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountactivation',
            name='bio',
        ),
    ]
