# Generated by Django 3.2.6 on 2022-03-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0037_remove_accountactivation_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountactivation',
            name='earn',
            field=models.IntegerField(default=0),
        ),
    ]
