# Generated by Django 3.2.6 on 2022-03-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0038_accountactivation_earn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountactivation',
            name='earn',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pending',
        ),
    ]
