# Generated by Django 3.2.6 on 2022-03-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0039_auto_20220319_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='balance',
        ),
        migrations.AlterField(
            model_name='accountactivation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disapproved'), (1, 'Approved'), (2, 'Denied')], default=0),
        ),
    ]
