# Generated by Django 3.2.6 on 2022-03-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0005_alter_profile_user'),
        ('refer', '0040_auto_20220319_1529'),
    ]

    operations = [
    ]
