# Generated by Django 3.2.6 on 2022-03-20 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refer', '0041_merge_0005_alter_profile_user_0040_auto_20220319_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountactivation',
            name='Payer_Wallet_Address',
            field=models.CharField(max_length=47, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='wallet_address',
            field=models.CharField(max_length=47),
        ),
    ]
