# Generated by Django 3.2.6 on 2022-03-20 22:01

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0045_auto_20220320_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='earn_dollar_currency',
            new_name='earn_currency',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='earn_dollar',
        ),
        migrations.AlterField(
            model_name='profile',
            name='earn',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=100, null=True),
        ),
    ]
