# Generated by Django 3.2.6 on 2022-03-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0046_auto_20220320_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='earn_currency',
        ),
        migrations.AlterField(
            model_name='profile',
            name='earn',
            field=models.IntegerField(default=4),
        ),
    ]
